version: '3.9'

services:
  first-container:
    container_name: 1st-container
    build:
      context: .
      target: app_prod
    ports:
      - "3000:8080"
    volumes:
      - "./:/app"

  second-container:
    container_name: 2nd-container
    build:
      context: .
      target: app_prod
    ports:
      - "3001:8080"
    volumes:
      - "./:/app"